name: kicons
description: An Icon package project,you can use many icons which you like.Then,you can list all of the icons quickly!
version: 1.0.2
author: jiangkang<jiangkang0504@gmail.com>
homepage: https://jiangkang.tech

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Emoji
      fonts:
        - asset: fonts/emoji.ttf
    - family: Aliyun
      fonts:
        - asset: fonts/aliyun.ttf
