targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
        generate_for:
          - test/multiplatform/**_test.dart
          - test/web/**_test.dart
          - web/**.dart
      build_vm_compilers|entrypoint:
        generate_for:
          - test/multiplatform/**_test.dart
          - test/vm/**_test.dart
          - bin/**.dart
      flutter_system|router_builder:
        enabled: true


builders:
  router_builder:
    import: 'package:flutter_system/frouter/router_builder.dart'
    builder_factories: ['routerBuilder']
    build_extensions: {'.dart': ['.router.dart']}
    auto_apply: root_package
    build_to: source
